Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.box = "bento/debian-13"
  
  config.vm.define "tbouzalmS" do |server|
    server.vm.hostname = "tbouzalmS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name  = "tbouzalmS"
    end
    server.vm.provision "shell", path: "scripts/server_script.sh"
  end
  
  config.vm.define "tbouzalmSW" do |server|
    server.vm.hostname = "tbouzalmSW"
    server.vm.network "private_network", ip: "192.168.56.111"
    server.vm.provider "virtualbox" do |vb|
      vb.name  = "tbouzalmSW"
    end
    server.vm.provision "shell", path: "scripts/server_worker_script.sh"
  end
end